version: '3'
services:
  webserver:
    image: httpd:latest
    volumes:
      - ./index.html:/usr/local/apache2/htdocs/index.html
      - ./styles.css:/usr/local/apache2/htdocs/styles.css
      - ./script.js:/usr/local/apache2/htdocs/script.js
    ports:
      - 8080:80
  websocket-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
